version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/config-docker.json:/usr/src/backend/config.json
    environment:
      - RUST_LOG=${RUST_LOG:-debug}
    ports:
      - 8088:8088
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080

