name: JS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
      # Setup npm
      - name: Install Node
        uses: actions/setup-node@v1
      # Install deps and run linter for frontend
      - run: npm install && npm run lint
        working-directory: frontend
      # Run tests for frontend
      - run: npm run test
        working-directory: frontend
