name: JS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - uses: actions/checkout@v2
      # Install npm and deps
      - name: Install Node
        uses: actions/setup-node@v1
      - run: npm install
      # Run linter
      - run: npm run lint
