name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy
        override: true
    - name: Clippy check
      uses: actions-rs/clippy-check@v1.0.5
      with:
        # GitHub token
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features --manifest-path ./backend/Cargo.toml
    - name: Build
      run: cargo build --verbose --manifest-path ./backend/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path ./backend/Cargo.toml
